[MeasureAudio1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1

[MeterRoundline1]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-1)-1))+(#RoundlineGap#*(Abs([Invert]-1)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-1))+(#RoundlineGap#*(Abs([Invert]-1)-1)))

[MeasureAudio2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2

[MeterRoundline2]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-2)-1))+(#RoundlineGap#*(Abs([Invert]-2)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-2))+(#RoundlineGap#*(Abs([Invert]-2)-1)))

[MeasureAudio3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3

[MeterRoundline3]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-3)-1))+(#RoundlineGap#*(Abs([Invert]-3)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-3))+(#RoundlineGap#*(Abs([Invert]-3)-1)))

[MeasureAudio4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4

[MeterRoundline4]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-4)-1))+(#RoundlineGap#*(Abs([Invert]-4)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-4))+(#RoundlineGap#*(Abs([Invert]-4)-1)))

[MeasureAudio5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5

[MeterRoundline5]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-5)-1))+(#RoundlineGap#*(Abs([Invert]-5)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-5))+(#RoundlineGap#*(Abs([Invert]-5)-1)))

[MeasureAudio6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6

[MeterRoundline6]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-6)-1))+(#RoundlineGap#*(Abs([Invert]-6)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-6))+(#RoundlineGap#*(Abs([Invert]-6)-1)))

[MeasureAudio7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7

[MeterRoundline7]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-7)-1))+(#RoundlineGap#*(Abs([Invert]-7)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-7))+(#RoundlineGap#*(Abs([Invert]-7)-1)))

[MeasureAudio8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8

[MeterRoundline8]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-8)-1))+(#RoundlineGap#*(Abs([Invert]-8)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-8))+(#RoundlineGap#*(Abs([Invert]-8)-1)))

[MeasureAudio9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9

[MeterRoundline9]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-9)-1))+(#RoundlineGap#*(Abs([Invert]-9)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-9))+(#RoundlineGap#*(Abs([Invert]-9)-1)))

[MeasureAudio10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10

[MeterRoundline10]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-10)-1))+(#RoundlineGap#*(Abs([Invert]-10)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-10))+(#RoundlineGap#*(Abs([Invert]-10)-1)))

[MeasureAudio11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11

[MeterRoundline11]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-11)-1))+(#RoundlineGap#*(Abs([Invert]-11)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-11))+(#RoundlineGap#*(Abs([Invert]-11)-1)))

[MeasureAudio12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12

[MeterRoundline12]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-12)-1))+(#RoundlineGap#*(Abs([Invert]-12)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-12))+(#RoundlineGap#*(Abs([Invert]-12)-1)))

[MeasureAudio13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13

[MeterRoundline13]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-13)-1))+(#RoundlineGap#*(Abs([Invert]-13)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-13))+(#RoundlineGap#*(Abs([Invert]-13)-1)))

[MeasureAudio14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14

[MeterRoundline14]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-14)-1))+(#RoundlineGap#*(Abs([Invert]-14)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-14))+(#RoundlineGap#*(Abs([Invert]-14)-1)))

[MeasureAudio15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15

[MeterRoundline15]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-15)-1))+(#RoundlineGap#*(Abs([Invert]-15)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-15))+(#RoundlineGap#*(Abs([Invert]-15)-1)))

[MeasureAudio16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16

[MeterRoundline16]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-16)-1))+(#RoundlineGap#*(Abs([Invert]-16)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-16))+(#RoundlineGap#*(Abs([Invert]-16)-1)))

[MeasureAudio17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17

[MeterRoundline17]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-17)-1))+(#RoundlineGap#*(Abs([Invert]-17)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-17))+(#RoundlineGap#*(Abs([Invert]-17)-1)))

[MeasureAudio18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18

[MeterRoundline18]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-18)-1))+(#RoundlineGap#*(Abs([Invert]-18)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-18))+(#RoundlineGap#*(Abs([Invert]-18)-1)))

[MeasureAudio19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19

[MeterRoundline19]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-19)-1))+(#RoundlineGap#*(Abs([Invert]-19)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-19))+(#RoundlineGap#*(Abs([Invert]-19)-1)))

[MeasureAudio20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20

[MeterRoundline20]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-20)-1))+(#RoundlineGap#*(Abs([Invert]-20)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-20))+(#RoundlineGap#*(Abs([Invert]-20)-1)))

[MeasureAudio21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21

[MeterRoundline21]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-21)-1))+(#RoundlineGap#*(Abs([Invert]-21)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-21))+(#RoundlineGap#*(Abs([Invert]-21)-1)))

[MeasureAudio22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22

[MeterRoundline22]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-22)-1))+(#RoundlineGap#*(Abs([Invert]-22)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-22))+(#RoundlineGap#*(Abs([Invert]-22)-1)))

[MeasureAudio23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23

[MeterRoundline23]
Meter=Roundline
MeterStyle=MeterRoundline
LineStart=(#CenterOffset#+(#RoundlineLength#*(Abs([Invert]-23)-1))+(#RoundlineGap#*(Abs([Invert]-23)-1)))
LineLength=(#CenterOffset#+(#RoundlineLength#*Abs([Invert]-23))+(#RoundlineGap#*(Abs([Invert]-23)-1)))